# This file was generated by GoReleaser. DO NOT EDIT.
cask "hc" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ce2c305575555a54d54bdb6fa7ecc690629dfa3445a71107bd6eca5261b8e6f0"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab50677511d2b3d43e8253e8146cc2524a05e266fc5005474450e37757538bb4"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc1dde7447bde0c154760d428758f7afdf3e7f0620ee68dc3f0cb32063b08b6b"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "774d203aed2490a4af0c39b2d24df5e4102ac88f664608e1d8307974fccacc7e"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hc"
  desc "A small, dependency-free CLI for the healthchecks.io Management API"
  homepage "https://github.com/matt17r/healthchecks-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hc"]
    end
  end

  # No zap stanza required

end
