# This file was generated by GoReleaser. DO NOT EDIT.
cask "hc" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "a5fa519de8fae603ab9bd4741a48c2d8b5aaffb00e59cbfa760967d5a2a2ef8d"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5b1a54139f3ab1375699449765872114e004b639d9999c4473fa735c38ca6bb"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4f075802b4afcbafd50d84fd32b0ac5e20cbe242d2d8ea60553b2fcdd1d3187"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "534dd2876d9827d95da07a2c2883a2c0dde5530c9401f180770a0f2335ff67a9"
      url "https://github.com/matt17r/healthchecks-cli/releases/download/v#{version}/hc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hc"
  desc "Small, dependency-free CLI for the healthchecks.io Management API"
  homepage "https://github.com/matt17r/healthchecks-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hc"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hc"] if OS.mac?
  end

  # No zap stanza required
end
